### ISSUE TITLE
When on you need to noclip to move around after.

### ISSUE THREAD

**Issue by HearingSubset19** [Andyyy7666/ND_Framework#14]
https://github.com/Andyyy7666/ND_Framework/blob/5720049448f707e2b11b745a3eafba2b1c1b1c3e/ND_CharacterSelection/config.lua#L6

![image](https://user-images.githubusercontent.com/45643254/179420099-88cf7e1e-95f1-4f19-a2e2-7d1d6b277f1d.png)

**Comment by Andyyy7666** [comment]
This isn't an issue with the character selection itself. You need to have latest versions of ModernHUD or SimpleHUD, make sure you also start it before starting the character selection.

**Comment by HearingSubset19** [comment]
Ok so just to be clear you are saying to have them in order like this?

ensure oxmysql
ensure ModernHUD
ensure ND_Core
ensure ND_CharacterSelection
ensure ND_Banks
ensure ND_ATMs
ensure ND_Chat
ensure ND_Doorlocks
ensure ND_Jailing
ensure ND_ShotSpotter

**Comment by Andyyy7666** [comment]
You might be using an older version of ModernHUD that doesn't have the export, causing it to return a nil value,

**Comment by HearingSubset19** [comment]
i downloaded it mid-day yesterday, ill redownload it again

**Comment by HearingSubset19** [comment]
The Issue Still persists...

When ModernHUD is started like this:
- ensure oxmysql
- ensure ModernHUD
- ensure ND_Core
- ensure ND_CharacterSelection
- ensure ND_Banks
- ensure ND_ATMs
- ensure ND_Chat
- ensure ND_Doorlocks
- ensure ND_Jailing
- ensure ND_ShotSpotter

Also if set to `characterSelectionAopDisplay = false,` for the first pic error. So ModernHUD needs to start after ND_Core

This happens:
![image](https://user-images.githubusercontent.com/45643254/179421642-d2e99629-2645-4cc7-9986-dbee6f86ed65.png)

Error Log:
![image](https://user-images.githubusercontent.com/45643254/179421669-5fa9187f-62eb-4780-adf4-0caf89594016.png)
======================================
When it is started like this:
- ensure oxmysql
- ensure ND_Core
- ensure ModernHUD
- ensure ND_CharacterSelection
- ensure ND_Banks
- ensure ND_ATMs
- ensure ND_Chat
- ensure ND_Doorlocks
- ensure ND_Jailing
- ensure ND_ShotSpotter

Also if set to `characterSelectionAopDisplay = false,` for the first pic Works just the other issues with it. 

This happens:
![image](https://user-images.githubusercontent.com/45643254/179421851-5c351359-c1c9-4b78-9f04-a6b5d501e199.png)

Error Log:
![image](https://user-images.githubusercontent.com/45643254/179421891-631b7565-04c0-4635-b4bc-4d8515b31d11.png)

**Comment by HearingSubset19** [comment]
I'll Just set it to false and not use it
