### ISSUE TITLE
Character Creation Dupe Bug

### ISSUE THREAD

**Issue by HearingSubset19** [Andyyy7666/ND_Framework#17]
**Describe the bug**
The departments duplicate within the character selection

**To Reproduce**
Not too Sure but load up and it is duplicated.

**Expected behavior**
Not to duplicate

**Screenshots**
![image](https://user-images.githubusercontent.com/45643254/179420021-92ede923-7b4b-4a83-822b-248ec2e561cd.png)

**Additional context**
Goes away after a restart of ND_CharacterSelection.

**Comment by Andyyy7666** [comment]
Are you using the latest version of ND_Core and ND_CharacterSelection

**Comment by HearingSubset19** [comment]
yes

**Comment by Franklee1995** [comment]
i have this issue as well all is up to date
