### ISSUE TITLE
Department Drop down not working 

### ISSUE THREAD

**Issue by argon1820** [Andyyy7666/ND_Framework#20]
On the "Create New Character 0/15" the department dropdown will not show when clicked. 

**To Reproduce**
launch game with no characters created > select "Create New Character 0/15" > select the "Department" dropdown

**Expected behavior**
Expect to see a dropdown of the departments

**Screenshots**
![image](https://user-images.githubusercontent.com/109833921/180584386-bb52331c-8b01-4436-bf0e-0c6426b45d8f.png)

**Comment by nik0-3d** [comment]
Do you have any errors

**Comment by argon1820** [comment]
My Apologies this was a PICNIC issue. Thanks anyways!!
