### ISSUE TITLE
Support for QBCore

### ISSUE THREAD

**Issue by xDope7137** [Andyyy7666/ND_Framework#22]
Am I allowed to make a new repo using your code for Fuel script and convert it for qb-core? With full credits and same script name obviously.

**Comment by Andyyy7666** [comment]
Yes that’s fine 👍

**Comment by xDope7137** [comment]
Thanks!

Here is the modified version!
https://github.com/xDope7137/ND_Fuel

**Comment by Andyyy7666** [comment]
Nice, I’ll add this into the forum post. There was some people asking for it to work with qb.
